# Generated by Django 5.2.6 on 2025-10-05 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_last_activity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='grade',
            field=models.CharField(blank=True, choices=[('CM2', 'CM2'), ('6ème', '6ème'), ('5ème', '5ème'), ('4ème', '4ème'), ('3ème', '3ème'), ('2nde', '2nde'), ('1ère', '1ère'), ('Tle', 'Tle')], max_length=10, null=True),
        ),
    ]
