# Generated by Django 5.2.7 on 2025-10-12 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_api', '0002_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='otp_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='admin',
            name='otp_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
