# Generated by Django 5.2.7 on 2025-10-10 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raw', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='COMPLETED', max_length=10),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('ADMIN_GRANT', 'Admin Grant'), ('TASK_REWARD', 'Task Reward'), ('TRANSFER_SEND', 'Transfer Send'), ('TRANSFER_RECEIVE', 'Transfer Receive'), ('SIGNUP_BONUS', 'Signup Bonus'), ('DAILY_LOGIN', 'Daily Login'), ('SHOP_REDEMPTION', 'Shop Redemption')], max_length=20),
        ),
    ]
