# Generated by Django 5.2.7 on 2025-10-10 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raw', '0002_transaction_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='product_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
