# Generated by Django 5.2.8 on 2025-11-22 22:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raw', '0003_transaction_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='recipient_wallet',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_transactions', to='raw.wallet'),
        ),
    ]
